spring.application.name=usuario-springboot
spring.datasource.url=jdbc:postgresql://localhost:5432/senasapp_db
spring.datasource.username=postgres
spring.datasource.password=magaly
spring.jpa.hibernate.ddl-auto=validate
server.port=8081